database:
  host: us-prod-upstream-api001-oriole-db.postgres.database.azure.com
  user_name: dhos-medications@us-prod-upstream-api001-oriole-db
  su_name: postgres@us-prod-upstream-api001-oriole-db
  name: dhos-medications

environment: PRODUCTION
imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config-prod during a release
imagetag: r1.12.0
allow_drop_data: false
host_env: azure

ingress:
  hostName: api-prod.sensynehealth.local
