database:
    user_password: ENC[AES256_GCM,data:MUI6v/8diJ3Qq3i63MUH5oHKeoLe69/zYhC5XOTZSlU=,iv:1pg+0DjPiV8eY30OejT+4ciNYg2nR0pYHs3Mz2bdJIQ=,tag:XAujG3s/syopn9z38PMGmw==,type:str]
    su_password: ENC[AES256_GCM,data:Eg67xciukGnxe0rFRy11RDGSt0q1t2l+LwrzX+ZdqNY=,iv:iEmGcyZ4xmUjqEvrVxQsFbS8INteRKpzg92gMLL5VtQ=,tag:sv7h9+wTyCd0uxgi1PxjTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://us-prod-keyvault.vault.azure.net
        name: dhos-medications-api-sops
        version: 5d719bd473474192a070e9ef9442c33a
        created_at: '2020-12-14T09:45:43Z'
        enc: QVNdJvPNbKzwCra9EiXMMMTB49zWLoSiR7dNehpJE36l1h8kL4zoR8cc3vfenXNyXWw9h1nFuPRnIToHs37kWbJopwN3poO4nOF_sl-1IrKrI65Q-PdAlq-a4AQqRVjlfee-OnsFDR-DMgLNj9Y8DVGcGxCRSMkAUfLtd3VRLPGb8HhTK90v-CFDF5_sohMax1fSzIsDBLvHcFrIhfVIB2ayEs8VqEKe_6IaR7f2u0CeXZaJsx8cdJ6hdRMHwXDTmCRlNH2McgfvbimzBKvYmKSEaRr73z06qy5eWQ4P3Cn1QKMWFS1DjLnkftbAHQyJw67v87OKpWEfAfzvJhBGQw
    hc_vault: []
    lastmodified: '2020-12-14T11:37:00Z'
    mac: ENC[AES256_GCM,data:D2woO/XmISe1yX0YIneRZAU+S6rcttp6AXlsOAZqFuQpMODIHC3lFiOAFzh7vX554g50eyWzBN4vUdyFC8u40o6lJN2UiCX6JrXZTH1PzfTIiQocbbbAb9i/pYeagE1NOAzOo/ulBQbl3IlX0cv4euxzT0INrZadUxPT74Iswmc=,iv:97j7EN7oaw1GszDEkH3hmN6Fl2LYFAwjorpRBYuY4TA=,tag:0hFhgElssQ7u0yNn+ihUDA==,type:str]
    pgp:
    -   created_at: '2020-12-14T09:45:45Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQf+LFTDRCoMbHWaWhhuRDPhwvrL1yenXdwzg0cOGTdDNYV7
            cAezhhgvdQHAdMUEuwqFyTCFrHLRHBP3B8A6ahirwtdkMpKjHSweEOhcZH2X6BOj
            1vxB1iV1rqkqcCdc/g8VzdcVLyLNQxirw9INZ3I0bRg0YexOiQpNsTg2sDlvfw9U
            y0+cImKaSoAAyW0/QbI2ADiagEPA7aiWWoMefki94SZBneJy1tFOGIyWLQzP+g2/
            5ljvGKhB0q8dsA+8wyIQGVkYeOLWR+GgZx5mb2gG3GPfaKV3ykiecDuzOKOhxVxY
            NzCdCcgjZs6T7FFs7CKRfnudDLX4s4zS4whBfj6ratJeAez5akR6qom1ynFy6CET
            HjDewwsJujKn5npz/Cc6eQgeamkelV1Ph6z74DTue/+oKqEZy5eqbpMT2N3wH+X5
            hCzh8ROmeHL9BLohfSArb3f0yAAdCoy+RSNmnDusZQ==
            =YMHE
            -----END PGP MESSAGE-----
        fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.6.1
