database:
  host: us-nonprod-upstream-api001-tomcat-db.postgres.database.azure.com
  user_name: dhos-medications@us-nonprod-upstream-api001-tomcat-db
  su_name: postgres@us-nonprod-upstream-api001-tomcat-db
  name: dhos-medications

environment: NONPRODUCTION
imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config (nonprod) devops-release-config-prod (prod) during a release
imagetag: r1.12.0
allow_drop_data: false
host_env: azure

ingress:
  hostName: api-nonprod.sensynehealth.local
