openapi: 3.0.3
info:
  description: The DHOS Medications API is responsible for storing and retrieving
    information about medications.
  title: DHOS Medications API
  version: 1.1.0
paths:
  /running:
    get:
      summary: Verify service is running
      description: Verifies that the service is running. Used for monitoring in kubernetes.
      tags:
      - monitoring
      responses:
        '200':
          description: If we respond, we are running
          content:
            application/json:
              schema:
                type: object
                properties:
                  running:
                    type: boolean
                    example: true
      operationId: flask_batteries_included.blueprint_monitoring.app_running
  /version:
    get:
      summary: Get version information
      description: Get the version number, circleci build number, and git hash.
      tags:
      - monitoring
      responses:
        '200':
          description: Version numbers
          content:
            application/json:
              schema:
                type: object
                properties:
                  circle:
                    type: string
                    example: '1234'
                  hash:
                    type: string
                    example: 366c204
      operationId: flask_batteries_included.blueprint_monitoring.app_version
  /dhos/v1/medication/{medication_id}:
    get:
      summary: Get medication
      description: Get a medication by UUID
      tags:
      - medication
      parameters:
      - name: medication_id
        in: path
        required: true
        description: The medication UUID
        schema:
          type: string
          example: 18439f36-ffa9-42ae-90de-0beda299cd37
      responses:
        '200':
          description: The requested medication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationResponse'
        default:
          description: Error, e.g. 404 Not Found, 503 Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: dhos_medications_api.blueprint_api.get_medication
    delete:
      summary: Delete medication
      description: Delete a medication by UUID
      tags:
      - medication
      parameters:
      - name: medication_id
        in: path
        required: true
        description: The medication UUID
        schema:
          type: string
          example: 18439f36-ffa9-42ae-90de-0beda299cd37
      responses:
        '200':
          description: The deleted medication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationResponse'
        default:
          description: Error, e.g. 400 Bad Request, 404 Not Found, 503 Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: dhos_medications_api.blueprint_api.delete_medication
    patch:
      summary: Update medication
      description: Update a medication by UUID
      tags:
      - medication
      parameters:
      - name: medication_id
        in: path
        required: true
        description: The medication UUID
        schema:
          type: string
          example: 18439f36-ffa9-42ae-90de-0beda299cd37
      requestBody:
        description: JSON body containing the medication fields to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedicationPatchRequest'
      responses:
        '200':
          description: The updated medication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationResponse'
        default:
          description: Error, e.g. 400 Bad Request, 404 Not Found, 503 Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: dhos_medications_api.blueprint_api.patch_medication
  /dhos/v1/medication:
    get:
      summary: Get all medications
      description: Get a list of all medications
      tags:
      - medication
      parameters:
      - name: tag
        in: query
        required: false
        description: Tag to filter medications by
        schema:
          type: string
          example: diabetes
      responses:
        '200':
          description: A list of all medications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedicationResponse'
        default:
          description: Error, e.g. 400 Bad Request, 404 Not Found, 503 Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: dhos_medications_api.blueprint_api.get_all_medications
    post:
      summary: Create new medication
      description: Create a new medication
      tags:
      - medication
      requestBody:
        description: JSON body containing the medication
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedicationRequest'
      responses:
        '200':
          description: The new medication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationResponse'
        default:
          description: Error, e.g. 400 Bad Request, 404 Not Found, 503 Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: dhos_medications_api.blueprint_api.create_medication
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          description: HTTP response code
          example: 404
        message:
          type: string
          description: Message attached to response
          example: Not Found
      required:
      - code
      description: An error response in json format
    MedicationSchema:
      type: object
      properties:
        sct_code:
          type: string
          minLength: 1
          example: '109081006'
          description: The SCT code of the medication
        name:
          type: string
          minLength: 1
          example: Metformin
          description: The name of the medication
        unit:
          type: string
          minLength: 1
          example: mmol
          description: The unit of the medication
        tags:
          type: array
          description: Tags with which the medication is associated
          items:
            type: string
            description: Tag name
            example: diabetes
      required:
      - name
      - sct_code
      - unit
      title: Medication fields common to request and response
    MedicationRequest:
      type: object
      properties:
        sct_code:
          type: string
          minLength: 1
          example: '109081006'
          description: The SCT code of the medication
        name:
          type: string
          minLength: 1
          example: Metformin
          description: The name of the medication
        unit:
          type: string
          minLength: 1
          example: mmol
          description: The unit of the medication
        tags:
          type: array
          description: Tags with which the medication is associated
          items:
            type: string
            description: Tag name
            example: diabetes
      required:
      - name
      - sct_code
      - unit
      title: Medication request
    MedicationPatchRequest:
      type: object
      properties:
        sct_code:
          type: string
          minLength: 1
          example: '109081006'
          description: The SCT code of the medication
        name:
          type: string
          minLength: 1
          example: Metformin
          description: The name of the medication
        unit:
          type: string
          minLength: 1
          example: mmol
          description: The unit of the medication
        tags:
          type: array
          description: Tags with which the medication is associated
          items:
            type: string
            description: Tag name
            example: diabetes
      title: Medication PATCH request
    MedicationResponse:
      type: object
      properties:
        sct_code:
          type: string
          minLength: 1
          example: '109081006'
          description: The SCT code of the medication
        name:
          type: string
          minLength: 1
          example: Metformin
          description: The name of the medication
        unit:
          type: string
          minLength: 1
          example: mmol
          description: The unit of the medication
        tags:
          type: array
          description: Tags with which the medication is associated
          items:
            type: string
            description: Tag name
            example: diabetes
        uuid:
          type: string
          description: Universally unique identifier for object
          example: 2c4f1d24-2952-4d4e-b1d1-3637e33cc161
        created:
          type: string
          description: When the object was created
          example: '2017-09-23T08:29:19.123+00:00'
        created_by:
          type: string
          description: UUID of the user that created the object
          example: d26570d8-a2c9-4906-9c6a-ea1a98b8b80f
        modified:
          type: string
          description: When the object was modified
          example: '2017-09-23T08:29:19.123+00:00'
        modified_by:
          type: string
          description: UUID of the user that modified the object
          example: 2a0e26e5-21b6-463a-92e8-06d7290067d0
      required:
      - name
      - sct_code
      - unit
      - uuid
      title: Medication response
  responses:
    BadRequest:
      description: Bad or malformed request was received
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServiceUnavailable:
      description: Service or dependent resource not available
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
