apiVersion: v1
kind: Secret
metadata:
  name: dhos-medications-api-secrets
  labels:
    app: dhos-medications-api
data:
  DATABASE_PASSWORD: {{ .Values.database.user_password | b64enc }}
  DATABASE_SU_PASSWORD: {{ .Values.database.su_password | b64enc }}
