apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: dhos-medications-api
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: dhos-medications-api
